apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Values.appname }}-configmap2
data:
    POSTGRES_USER: {{ .Values.log.username }}
    POSTGRES_DB: {{ .Values.log.database }}
    HOSTNAME: {{ .Values.log.hostname }}